config/routes.rb
ShoppingList::Application.routes.draw do
  resources :lists do
    member do
      post :add_product
      put :close
    end
  end

  resources :products do
    member do
      put :bought
    end
  end

  devise_for :users
  root to: "lists#index"
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :products
  belongs_to :user

  def close
    update(status: "closed")
  end

  def closed?
    status == "closed"
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :list
  belongs_to :user
  delegate :email, to: :user, prefix: true 
  scope :bought, ->{where(status: "bought")}
  scope :fresh, ->{where(status: "new")}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :lists
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :add_product, :close]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @product = Product.new
    @products = current_user.products.where(list: @list).fresh
    @boughts = current_user.products.where(list: @list).bought
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  def close
   @list.close
    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(user: current_user)
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list }
      else
        format.html { render action: 'new' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_product
    product = Product.new(name: params[:product][:name],list: @list, user: current_user)
    respond_to do |format|
      if product.save
        format.html { redirect_to @list, notice: "Product added success" }
      else
        format.html { redirect_to @list, notice: "Something went wrong" }
      end
    end
  end
  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:user_id, :status)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :bought]

  # GET /products
  # GET /products.json
  def index
    @products = current_user.products
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end


  # PUT /products/1
  # 
  def bought
      if @product.user == current_user
         @product.update(status: "bought")
         @boughts = current_user.products.where(list: @product.list, status: "bought")
         render partial: "boughts", object: @boughts
      else
        render nothing: true, status: :unprocessable_entity
      end
  end
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
      render  nothing: true, status: :ok 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :status, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-danger"
    when :alert then "alert alert-warning"
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingList</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-5">
      <%= link_to('Lists',lists_path) %> |
      <%= link_to('My account', edit_user_registration_path) %> |
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %></div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div id="notices">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <%= value %>
        </div>
      <% end %>
      </div>
     <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/lists/index.html.erb
<h1>ShoppingLists :</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Status</th>
      <th>Date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
      <% @lists.each do |list| %>
        <tr>
          <td><%= list.status %></td>
          <td><%= list.updated_at %> </td>
          <td><%= link_to 'Show', list, class: "btn btn-primary btn-sm" %>
          <%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New List', lists_path, method: :post, class: "btn btn-success btn-sm" %>

app/views/lists/show.html.erb
<% unless @list.closed? %>
<h1>To buy</h1>
<table id="product-list" class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
     <%= simple_form_for @product, url: add_product_list_path(@list) do |f| %>
    <tr>
      <td style="width:250px;"><%= f.input_field :name %></td>
      <td style="width:250px;"> <%= f.submit "Add Product" , class: "btn btn-primary" %></td>
    </tr>
  <% end %>
  <% @products.each do |product| %>
    <tr>
      <td> <%= product.name %> </td>
      <td>
        <%= link_to "Bought", bought_product_path(product), data: {id: product.id }, class: "btn btn-primary btn-sm bought_product"%>
        <%= link_to "Remove", products_path(product), data: {id: product.id }, class: "btn btn-danger btn-sm remove_product" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Close List", close_list_path(@list), method: "put",  class: "btn btn-danger btn-sm remove_product" %>
<% end %>
<h1>Bought</h1>
<center>
<div id="boughts">
<table id="product-list" style="max-width:200px;" class="table table-responsive table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @boughts.each do |product| %>
    <tr>
      <td> <%= product.name %> </td>
      <td>
         <%= link_to "Remove", products_path(product), data: {id: product.id }, class: "btn btn-danger btn-sm remove_product" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
</center>
<%= link_to 'Back', lists_path %>

app/views/products/_boughts.html.erb
<table id="product-list" style="max-width:200px;" class="table table-responsive table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @boughts.each do |product| %>
    <tr>
      <td> <%= product.name %> </td>
      <td>
         <%= link_to "Remove", products_path(product), data: {id: product.id }, class: "btn btn-danger btn-sm remove_product" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :status %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.status %></td>
        <td><%= product.user_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @product.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>